kind: Template
apiVersion: v1
metadata:
  name: mongodb-shard-aws-on-openshift
  annotations:
    openshift.io/display-name: "AWS MongoDB Shard"
    description: "MongoDB Shard on OpenShift, AWS Hosted"
    iconClass: "icon-mongodb"
    tags: "database,mongodb,nosql"
parameters:
  - name: MONGODB_USER
    displayName: "MongoDB Connection Username"
    description: "Username for MongoDB user that will be used for client connections"
    generate: expression
    from: "[a-zA-Z0-9]{3}"
    required: true

  - name: MONGODB_PASSWORD
    displayName: "MongoDB Connection Password"
    description: "Password for the MongoDB connection user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_DATABASE
    displayName: "MongoDB Database Name"
    description: "Name of a sample MongoDB database to initialize"
    value: sampledb
    required: true

  - name: MONGODB_ADMIN_PASSWORD
    displayName: "MongoDB Admin Password"
    description: "Password for the admin user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_SHARD_REPLICA_NAME
    displayName: "Shard Replica Set Name"
    description: "The name of the shard replica set."
    value: rs0
    required: true

  - name: MONGODB_KEYFILE_VALUE
    displayName: "Keyfile Content"
    description: "The value of the MongoDB keyfile for inter-cluster communication. Must be the same throughout the cluster. See (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
    generate: expression
    from: "[a-zA-Z0-9]{255}"
    required: true

  - name: MONGODB_IMAGE
    displayName: "MongoDB Docker Image"
    description: "A reference to a supported MongoDB Docker image."
    value: "bornemannjs/mongodb-34:0.56"
    required: true

  - name: VOLUME_CAPACITY
    displayName: "Volume Capacity"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    value: "1Gi"
    required: true

  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "512Mi"

  - name: SHARD_SEED
    displayName: "Shard seed"
    description: "For creating unique objects from this template in a sharded environment. A value will be generated. Nothing to do here."
    generate: expression
    from: "[a-z]{3}"

objects:
  # A headless service to create DNS records
  - kind: Service
    apiVersion: v1
    metadata:
      name: "mongodb-shard-internal-${SHARD_SEED}"
      labels:
        app: mongodb
        shard_seed: "${SHARD_SEED}"
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:
      clusterIP: None
      # the list of ports that are exposed by this service
      ports:
        - name: mongodb
          port: 27017
      # will route traffic to pods having labels matching this selector
      selector:
        name: "mongodbshard${SHARD_SEED}"

  - kind: StatefulSet
    apiVersion: apps/v1beta1
    metadata:
      app: mongodb
      name: "mongodbshard${SHARD_SEED}"
    spec:
      # pets get DNS/hostnames that follow the pattern: ${metadata.name}-NUM.${spec.serviceName}.default.svc.cluster.local
      serviceName: "mongodb-shard-internal-${SHARD_SEED}"
      replicas: 4
      # describes the pod that will be created if insufficient replicas are detected
      template:
        metadata:
          labels:
            name: "mongodbshard${SHARD_SEED}"
            shard_seed: "${SHARD_SEED}"
            app: "mongodb"
        spec:
          containers:
            - name: mongo-container
              image: "${MONGODB_IMAGE}"
              ports:
                - containerPort: 27017
              args:
                - "run-replset"
              volumeMounts:
                - name: mongo-data
                  mountPath: "/var/lib/mongodb/data"
              env:
                - name: MONGODB_USER
                  value: "${MONGODB_USER}"
                - name: MONGODB_PASSWORD
                  value: "${MONGODB_PASSWORD}"
                - name: MONGODB_DATABASE
                  value: "${MONGODB_DATABASE}"
                - name: MONGODB_ADMIN_PASSWORD
                  value: "${MONGODB_ADMIN_PASSWORD}"
                - name: MONGODB_REPLICA_NAME
                  value: "${MONGODB_SHARD_REPLICA_NAME}"
                - name: MONGODB_KEYFILE_VALUE
                  value: "${MONGODB_KEYFILE_VALUE}"
                - name: MONGODB_SERVICE_NAME
                  value: "mongodb-shard-internal-${SHARD_SEED}"
                - name: SHARD_ENABLED
                  value: "true"
                - name: ENABLE_TLS
                  valueFrom:
                    configMapKeyRef:
                      name: shard-${SHARD_SEED}-config
                      key: ssl.enabled
                - name: SSL_CA_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: shard-${SHARD_SEED}-config
                      key: ssl.ca.path
                - name: ADDITIONAL_SSL_OPTS
                  valueFrom:
                    configMapKeyRef:
                      name: shard-${SHARD_SEED}-config
                      key: additional.ssl.opts

              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
              livenessProbe:
                initialDelaySeconds: 60
                tcpSocket:
                  port: 27017
              readinessProbe:
                initialDelaySeconds: 10
                exec:
                  command:
                    - "mongo-is-ready"
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
            labels:
              app: mongodb
              shard_seed: "${SHARD_SEED}"
            annotations:
              volume.beta.kubernetes.io/storage-class: us-east-storage
          spec:
            accessModes: [ ReadWriteOnce ]
            resources:
              requests:
                storage: "${VOLUME_CAPACITY}"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: shard-${SHARD_SEED}-config
      app: mongodb
    data:
      ssl.enabled: "true"
      ssl.ca.path: ""
      additional.ssl.opts: "--sslAllowConnectionsWithoutCertificates --sslDisabledProtocols TLS1_0,TLS1_1"
